table Orders
	lineageTag: 35e2b2e4-71bc-4392-bc70-8533ef88a601

	column OrderID
		dataType: int64
		formatString: 0
		lineageTag: 2750fce1-a9f9-4c39-a8ef-1c1b6d3cd3f1
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 7b44b1f8-efbd-4c50-932b-ea824896737a
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: 3996c971-53e5-4f42-86fe-fe8992c0028c
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 440fd544-f01f-4374-827e-13013f0bb4c8
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9f309e8c-7d98-49c1-89ac-f582f722c60f
		summarizeBy: none
		sourceColumn: OrderDate

		variation Variation
			isDefault
			relationship: 7c6951bc-909b-471d-a1ae-67aa547edb49
			defaultHierarchy: LocalDateTable_0cb1704c-5bb2-4db3-b154-c258e1ca83c2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\mardin\Downloads\Skill Mentors Data Set [Excel]\Orders.xlsx"), null, true),
				    Orders_Sheet = Source{[Item="Orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"OrderID", Int64.Type}, {"CustomerID", Int64.Type}, {"ProductID", Int64.Type}, {"Quantity", Int64.Type}, {"OrderDate", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

