table 'Project Members'
	lineageTag: 6ad114b3-74df-4f65-b4f0-4a7e5582bbe4

	column ProjectID
		dataType: int64
		formatString: 0
		lineageTag: f81224ab-7f87-4863-80b8-1f471749e412
		summarizeBy: count
		sourceColumn: ProjectID

		annotation SummarizationSetBy = Automatic

	column EmployeeID
		dataType: int64
		formatString: 0
		lineageTag: 3b45f06b-9819-4e4e-b218-4bf654600b15
		summarizeBy: none
		sourceColumn: EmployeeID

		annotation SummarizationSetBy = Automatic

	column Role
		dataType: string
		lineageTag: dfe3d6ee-90ce-4bd9-95e0-238039599846
		summarizeBy: none
		sourceColumn: Role

		annotation SummarizationSetBy = Automatic

	partition 'Project Members' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\mardin\Downloads\Skill Mentors Data Set [Excel]\Project Members.xlsx"), null, true),
				    #"Project Members_Sheet" = Source{[Item="Project Members",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Project Members_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProjectID", Int64.Type}, {"EmployeeID", Int64.Type}, {"Role", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

