table Sheet1
	lineageTag: bd26c03c-1367-43b2-909d-cb5bd8a416a1

	column EmployeeID
		dataType: int64
		formatString: 0
		lineageTag: dc5d42f7-5547-4d35-bb09-b6e5e9dcb4df
		summarizeBy: none
		sourceColumn: EmployeeID

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 5019a826-fa0d-4633-a54f-40c3fa06f680
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: e924a59a-4cc2-480b-be45-8d188f1e3951
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column DepartmentID
		dataType: int64
		formatString: 0
		lineageTag: 2adc76f0-ca09-4ecc-bd3c-25baecc5e60f
		summarizeBy: none
		sourceColumn: DepartmentID

		annotation SummarizationSetBy = Automatic

	partition Sheet1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\mardin\Downloads\Skill Mentors Data Set [Excel]\Employees.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"EmployeeID", Int64.Type}, {"FirstName", type text}, {"LastName", type text}, {"DepartmentID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

