table SuppliersProduct
	lineageTag: 9d49718b-32c2-4127-a69a-96f82374ae49

	column id
		dataType: int64
		formatString: 0
		lineageTag: 7cd5288d-692a-4882-acf9-c9b9f0e79cb7
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column SupplierID
		dataType: int64
		formatString: 0
		lineageTag: 28bee6e5-5b77-4872-aa13-be16dbad3fa9
		summarizeBy: none
		sourceColumn: SupplierID

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: 1e6c8062-3f20-4977-a8ec-070eff421c4c
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	partition SuppliersProduct = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\mardin\Downloads\Skill Mentors Data Set [Excel]\Suppliers.xlsx"), null, true),
				    SuppliersProduct_Sheet = Source{[Item="SuppliersProduct",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(SuppliersProduct_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"SupplierID", Int64.Type}, {"ProductID", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

